"""add sobriety_status to foundational_memory

Revision ID: 0acc131ea306
Revises: dfed2d9fa29e
Create Date: 2026-06-29 06:56:36.599774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acc131ea306'
down_revision: Union[str, Sequence[str], None] = 'dfed2d9fa29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foundational_memories', sa.Column('sobriety_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foundational_memories', 'sobriety_status')
    # ### end Alembic commands ###
