"""add user session conversationlog foundationalmemory tables

Revision ID: b89cb724c744
Revises: 1b47b3daaed2
Create Date: 2026-05-26 15:02:51.048784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89cb724c744'
down_revision: Union[str, Sequence[str], None] = '1b47b3daaed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
