"""
app/models/user.py — User model
=================================
Owner: B3 (SC-013)

The User table is the root of everything.
Every other table links back to User via foreign key.

Field decisions:
  - UUID primary key — not integer. Integer IDs are guessable.
  - email stored lowercase always — normalised in repository layer.
  - hashed_password — bcrypt hash only. Plain password never stored.
  - sobriety_start_date — nullable. User may not know exact date.
  - framework_orientation — drives companion language choices.
  - is_active — soft delete. Never hard-delete a user.
"""

import uuid
from datetime import date
from enum import Enum
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Boolean, Date, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.foundational_memory import FoundationalMemory
    from app.models.session import CompanionSession


class FrameworkOrientation(str, Enum):
    """
    Recovery framework the user identifies with.
    Drives companion voice and language on every message turn.

    AA       → uses: 'higher power', 'steps', 'sponsor', 'meeting'
    SMART    → uses: 'motivation tools', 'cost-benefit', 'rational emotive'
    SECULAR  → no spiritual language at all
    SPIRITUAL → spiritual but not AA specifically
    UNDECIDED → neutral language that works for everyone (default)
    """
    AA        = "aa"
    SMART     = "smart"
    SECULAR   = "secular"
    SPIRITUAL = "spiritual"
    UNDECIDED = "undecided"


class User(Base, TimestampMixin):
    """
    Core user account.

    Inherits created_at and updated_at from TimestampMixin.
    Both are set automatically by PostgreSQL — never pass them manually.

    Relationships:
        sessions           → all companion sessions (one-to-many)
        foundational_memory → the user's profile memory (one-to-one)
    """

    __tablename__ = "users"

    # ------------------------------------------------------------------ #
    # Primary key
    # ------------------------------------------------------------------ #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="UUID primary key. Generated by Python on insert. Never integer.",
    )

    # ------------------------------------------------------------------ #
    # Identity
    # ------------------------------------------------------------------ #
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        doc=(
            "Login email. Always stored lowercase — call email.lower().strip() "
            "before inserting. Indexed — every login query filters by email."
        ),
    )

    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc=(
            "bcrypt hash of the password. Plain password is NEVER stored. "
            "passlib[bcrypt] creates this hash in the auth service."
        ),
    )

    # ------------------------------------------------------------------ #
    # Recovery profile
    # ------------------------------------------------------------------ #
    sobriety_start_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        doc=(
            "Date sobriety began. Nullable — user may not know exact date "
            "or may be in pre-sobriety contemplation phase. "
            "PHI — handle carefully. Never log this field."
        ),
    )

    framework_orientation: Mapped[FrameworkOrientation] = mapped_column(
        String(20),
        nullable=False,
        default=FrameworkOrientation.UNDECIDED,
        doc=(
            "Recovery framework alignment. Drives companion language. "
            "Default is undecided — neutral language until onboarding."
        ),
    )

    # ------------------------------------------------------------------ #
    # Account state
    # ------------------------------------------------------------------ #
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        doc=(
            "Soft-delete flag. False = account deactivated, cannot log in. "
            "Data is preserved — never hard-delete a user record."
        ),
    )

    # ------------------------------------------------------------------ #
    # Relationships
    # ------------------------------------------------------------------ #
    sessions: Mapped[List["CompanionSession"]] = relationship(
        "CompanionSession",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    foundational_memory: Mapped[Optional["FoundationalMemory"]] = relationship(
        "FoundationalMemory",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"<User id={self.id} "
            f"email={self.email} "
            f"active={self.is_active}>"
        )